name: flow-manager-app

services:

#  java-spring-app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flow_manager
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: 12345
#      SPRING_PROFILES_ACTIVE: local
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - flow-manager-net

  postgres:
    image: postgres:15
    container_name: postgres_db_flow_manager
    environment:
      POSTGRES_DB: flow_manager
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - flow-manager-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d flow_manager" ]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8.8-alpine
    container_name: my-redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - flow-manager-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9100:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flow-manager-net
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9090" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - flow-manager-net
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  flow-manager-net:
    driver: bridge

volumes:
  pg_data:
  redis-data:
  grafana-storage: